### ISSUE TITLE
Logo Design: CuteHMI

### ISSUE THREAD

**Issue by baranpirincal** [michpolicht/CuteHMI#1]
Hey!

I am graphic designer and my motivations are supporting open source project and making my portfolio better. Do you need a logo design? If you interested I want to design it as soon as possible!

Best Regards
Baran Pirinçal

**Comment by michpolicht** [comment]
Hi!
Any contribution would be welcomed, tho' I kinda like the idea behind the current [logo](https://github.com/michpolicht/CuteHMI/blob/master/doc/images/project_logo.png) - shape on the left symbolizes human, rectangle symbolizes machine and 'i' stands for interface between them. Letters HMI can be seen in current logo. But if you can do better or redesign the current logo, then it would be very welcomed!

Kind Regads
MP

**Comment by baranpirincal** [comment]
@michpolicht 

Hey again!

I got the idea of current logo design but I think that it would be better if I can re-design it. I will show my first experiments as soon as possible.

Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
@michpolicht 

Hey, sorry for delay. I was too busy last week.

I made my first experiments. We can change the colors or something on design.  I am waiting your comments.

![untitled-1](https://user-images.githubusercontent.com/37786733/43577797-83d448ca-9655-11e8-8f49-44c03acd7c3e.jpg)

**Comment by baranpirincal** [comment]
@michpolicht 

Hey, sorry for delay. I was too busy last week.

I made my first experiments. We can change the colors or something on design.  I am waiting your comments.

![untitled-1](https://user-images.githubusercontent.com/37786733/43577797-83d448ca-9655-11e8-8f49-44c03acd7c3e.jpg)

Best Regards
Baran Pirinçal

**Comment by michpolicht** [comment]
Hia!

I like the first one very much! Beside references to old logo, it reminds me some robotic character from a classic top-down shooter, such as Alien Breed...

![Alien Breed screenshot](https://user-images.githubusercontent.com/2004343/43676875-7ddc444a-97f9-11e8-9062-d8db4d96a477.png)

I have added you to contributors, so you can create `logo` branch and push your works to `extra/logo` directory if you wish. But if you prefer fork/pull request, then no problem.

It would be good if you could pick the license for your work or confirm that you are happy with MPL 2.0. According to [MPL FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)

> Q18: Should MPL be used for non-software works?
> MPL was written with software in mind, and should generally only be used for software. However, for consistency and simplicity, it may be appropriate to use the MPL for non-software works (such as documentation, images, and sound files) that are written primarily for use in MPL-licensed software.
>

Kind Regards
MP

**Comment by baranpirincal** [comment]
@michpolicht 

Hey, I am happy you liked it!

I uploaded all necessary files and created pull-request!

Good luck with that.

Best Regards
Baran Pirinçal

**Comment by michpolicht** [comment]
@baranpirincal 

Merged it. 

Thank you for the contribution!

**Comment by michpolicht** [comment]
@GitCash send .0015 bch to @baranpirincal

**Comment by GitCash** [comment]
Hey **baranpirincal**, user **michpolicht** tipped you **1500 bits** in Bitcoin Cash ( ~ **$0.7875** ).

*[Click here to claim it!](https://gitcash.io/claim/baranpirincal)*

You can also add the "thumbs down" reaction to **michpolicht**'s comment above to prevent future tips.

**Comment by michpolicht** [comment]
@GitCash send .015 bch to @baranpirincal

**Comment by GitCash** [comment]
Hey **baranpirincal**, user **michpolicht** tipped you **15000 bits** in Bitcoin Cash ( ~ **$7.875** ).

*[Click here to claim it!](https://gitcash.io/claim/baranpirincal)*

You can also add the "thumbs down" reaction to **michpolicht**'s comment above to prevent future tips.

**Comment by baranpirincal** [comment]
@michpolicht 

Thank you a lot for your support! :)
